### ISSUE TITLE
Compilation failed without any reason :(

### ISSUE THREAD

**Issue by bambosan** [SurvivalApparatusCommunication/RenderDragonSourceCodeInv#1]
![Screenshot 2023-06-21 221345](https://github.com/SurvivalApparatusCommunication/RenderDragonSourceCodeInv/assets/63803423/534e1996-9530-41af-9da9-86937caa69a7)

**Comment by bambosan** [comment]
I've checked some existing .bat files, but I think everything is fine

**Comment by ddf8196** [comment]
It seems that shaderc exits with a non-zero exit code, but no error message is given

**Comment by bambosan** [comment]
So is there a solution?

**Comment by ddf8196** [comment]
Unable to reproduce on my computer. 
Try compiling manually using MaterialBinTool and see if it works

**Comment by bambosan** [comment]
oh ok

**Comment by bambosan** [comment]
lemme check

**Comment by ddf8196** [comment]
You can also try to see if you can run `./env/MaterialBinTool-0.8.1/shaderc.exe` directly

**Comment by bambosan** [comment]
still failed :(

**Comment by bambosan** [comment]
> You can also try to see if you can run `./env/MaterialBinTool-0.8.1/shaderc.exe` directly

I tried it and not giving any output

**Comment by bambosan** [comment]
![Screenshot 2023-06-21 231113](https://github.com/SurvivalApparatusCommunication/RenderDragonSourceCodeInv/assets/63803423/27768cd9-e3b3-41aa-9f01-56ef55ec5b94)
it seems failed to run

**Comment by ddf8196** [comment]
Try to execute `echo $LASTEXITCODE` to see the exitcode

**Comment by bambosan** [comment]
output: -1073741795

**Comment by bambosan** [comment]
I try run the previous version and:
![Screenshot 2023-06-21 231751](https://github.com/SurvivalApparatusCommunication/RenderDragonSourceCodeInv/assets/63803423/44fb1292-6fdc-4648-a1dc-36e6dd79d25e)

**Comment by ddf8196** [comment]
It seems that the illegal instruction exception (0xC000001D) is causing shaderc to not start on your computer

**Comment by ddf8196** [comment]
shaderc.exe may be corrupted, try downloading it again from the latest github release

**Comment by ddf8196** [comment]
I have added the file SHA-256 to the latest Release description of MaterialBinTool, you can compare it to determine if shaderc.exe is corrupted

**Comment by bambosan** [comment]
It's same but still can't launch, idk this was caused by my computer or not :(
no need to worry, I can still use previous version of shaderc

**Comment by ddf8196** [comment]
What is your CPU?

**Comment by bambosan** [comment]
Intel Celeron n4000
Gemini Lake

**Comment by ddf8196** [comment]
I reproduced this problem on QEMU and confirmed that the problem is caused by the fact that bgfx currently has the AVX instruction set enabled by default, but your CPU doesn't support it.

**Comment by ddf8196** [comment]
Try this recompiled shaderc that doesn't use AVX instructions. if it's ok, I'll upload it to the latest release of MaterialBinTool.
[shaderc-NoAVX.zip](https://github.com/SurvivalApparatusCommunication/RenderDragonSourceCodeInv/files/11854026/shaderc-NoAVX.zip)

**Comment by bambosan** [comment]
It works now!
Huge thanks for this 😭
![Screenshot 2023-06-24 101748](https://github.com/SurvivalApparatusCommunication/RenderDragonSourceCodeInv/assets/63803423/5b8fcc5a-10e0-458d-89ba-d8e13a01619d)
