### ISSUE TITLE
Requesting src for BlockSelectionOverlay

### ISSUE THREAD

**Issue by Furzide** [SurvivalApparatusCommunication/RenderDragonSourceCodeInv#2]
hello, i want to make modifications to the selection box/overlay, but there is currently no src. if you could find src for things related to block selection overlay and ui3d, that would be great!

**Comment by GameParrot** [comment]
I put basic BlockSelectionOverlay src in my fork at https://github.com/GameParrot/RenderDragonSourceCodeInv
